name: drops_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.9.0-97.0.dev

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  flutter_shaders: ^0.1.2
  flutter_animate: ^4.3.0
  provider: ^6.1.1
  google_fonts: ^6.2.1
  path_provider: ^2.1.2
  shared_preferences: ^2.2.2
  uuid: ^4.5.1
  url_launcher: ^6.3.1
  audioplayers: ^6.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    # Explicitly include sub-directories; Flutter currently doesn't pick up
    # nested folders when the parent directory contains no files of its own.
    - assets/img/
    - assets/img/covers/
    - assets/img/artists/
    - assets/music/
    - assets/google_fonts/Alumni_Sans/
    - assets/google_fonts/Averia_Serif_Libre/
    # - assets/google_fonts/Orbitron/  # Removed - using League version instead
    - assets/google_fonts/Anaheim/
    - assets/google_fonts/Danfo/
    - assets/google_fonts/Bree_Serif/
    - assets/google_fonts/Young_Serif/
    - assets/google_fonts/Oxanium/
    - assets/google_fonts/Geist_Mono/
    - assets/google_fonts/MuseoModerno/
    - assets/google_fonts/DM_Serif_Display/
    - assets/google_fonts/Lexend_Deca/
    - assets/google_fonts/Pixelify_Sans/
    - assets/google_fonts/Gemunu_Libre/
    - assets/google_fonts/Podkova/
    - assets/google_fonts/Tourney/
    - assets/google_fonts/Instrument_Serif/
    - assets/google_fonts/Tektur/
    - assets/google_fonts/Asap_Condensed/
    - assets/fonts/league/
    - assets/fonts/fontesk/KyivType-VariableGX/
    - assets/fonts/fontesk/

  shaders:
    - assets/shaders/color_effect.frag
    - assets/shaders/blur_effect.frag
    - assets/shaders/noise_effect.frag
    - assets/shaders/rain_effect.frag
    - assets/shaders/chromatic_effect.frag
    - assets/shaders/ripple_effect.frag


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package

  fonts:
    - family: Danfo
      fonts:
        - asset: assets/google_fonts/Danfo/Danfo[ELSH].ttf
    - family: Geist Mono
      fonts:
        - asset: assets/google_fonts/Geist_Mono/GeistMono[wght].ttf
    - family: League Gothic
      fonts:
        - asset: assets/fonts/league/LeagueGothic-Regular.ttf
    - family: League Spartan
      fonts:
        - asset: assets/fonts/league/LeagueSpartan-VF.ttf
    - family: Ostrich Sans
      fonts:
        - asset: assets/fonts/league/ostrich-sans-regular.ttf
          weight: 400
        - asset: assets/fonts/league/ostrich-sans-bold.ttf
          weight: 700
        - asset: assets/fonts/league/ostrich-sans-black.ttf
          weight: 900
        - asset: assets/fonts/league/ostrich-sans-light.ttf
          weight: 300
        - asset: assets/fonts/league/OstrichSans-Medium.otf
          weight: 500
        - asset: assets/fonts/league/OstrichSans-Heavy.otf
          weight: 800
    - family: Orbitron
      fonts:
        - asset: assets/fonts/league/Orbitron Medium.ttf
          weight: 500
        - asset: assets/fonts/league/Orbitron Light.ttf
          weight: 300
        - asset: assets/fonts/league/Orbitron Bold.ttf
          weight: 700
        - asset: assets/fonts/league/Orbitron Black.ttf
          weight: 900
        - asset: assets/fonts/league/Orbitron Medium.otf
          weight: 500
        - asset: assets/fonts/league/Orbitron Light.otf
          weight: 300
        - asset: assets/fonts/league/Orbitron Bold.otf
          weight: 700
        - asset: assets/fonts/league/Orbitron Black.otf
          weight: 900
        - asset: assets/fonts/league/orbitron-medium-webfont.ttf
          weight: 500
        - asset: assets/fonts/league/orbitron-light-webfont.ttf
          weight: 300
        - asset: assets/fonts/league/orbitron-bold-webfont.ttf
          weight: 700
        - asset: assets/fonts/league/orbitron-black-webfont.ttf
          weight: 900
    - family: Knewave
      fonts:
        - asset: assets/fonts/league/knewave.ttf
        - asset: assets/fonts/league/knewave.otf
        - asset: assets/fonts/league/knewave-webfont.ttf
        - asset: assets/fonts/league/knewave-outline.ttf
          style: italic
        - asset: assets/fonts/league/knewave-outline.otf
          style: italic
        - asset: assets/fonts/league/knewave-outline-webfont.ttf
          style: italic
    - family: Junction
      fonts:
        - asset: assets/fonts/league/junction-regular.ttf
        - asset: assets/fonts/league/junction-light.ttf
          weight: 300
        - asset: assets/fonts/league/junction-bold.ttf
          weight: 700
    - family: Goudy Bookletter 1911
      fonts:
        - asset: assets/fonts/league/goudy_bookletter_1911-webfont.ttf
        - asset: assets/fonts/league/GoudyBookletter1911.otf
    - family: Blackout Sunrise
      fonts:
        - asset: assets/fonts/league/blackout_sunrise-webfont.ttf
        - asset: assets/fonts/league/Blackout Sunrise.ttf
    - family: Blackout Midnight
      fonts:
        - asset: assets/fonts/league/blackout_midnight-webfont.ttf
        - asset: assets/fonts/league/Blackout Midnight.ttf
    - family: Blackout Two AM
      fonts:
        - asset: assets/fonts/league/blackout_two_am-webfont.ttf
        - asset: assets/fonts/league/Blackout Two AM.ttf
        - asset: assets/fonts/league/Blackout 2 AM.ttf
    - family: Sniglet
      fonts:
        - asset: assets/fonts/league/Sniglet-webfont.ttf
        - asset: assets/fonts/league/Sniglet Regular.ttf
        - asset: assets/fonts/league/Sniglet Regular.otf
    - family: Linden Hill
      fonts:
        - asset: assets/fonts/league/LindenHill-webfont.ttf
        - asset: assets/fonts/league/LindenHill-Italic-webfont.ttf
          style: italic
        - asset: assets/fonts/league/Linden Hill.otf
        - asset: assets/fonts/league/Linden Hill Italic.otf
          style: italic
    - family: League Script
      fonts:
        - asset: assets/fonts/league/LeagueScriptNumberOne-webfont.ttf
        - asset: assets/fonts/league/LeagueScriptNumberOne.otf
    - family: Ostrich Sans Inline
      fonts:
        - asset: assets/fonts/league/ostrich-sans-inline-regular.ttf
        - asset: assets/fonts/league/ostrich-sans-inline-italic.ttf
          style: italic
        - asset: assets/fonts/league/OstrichSansInline-Regular.otf
        - asset: assets/fonts/league/OstrichSansInline-Italic.otf
          style: italic
    - family: Ostrich Sans Rounded
      fonts:
        - asset: assets/fonts/league/ostrich-sans-rounded.ttf
        - asset: assets/fonts/league/OstrichSansRounded-Medium.otf
    - family: Ostrich Sans Dashed
      fonts:
        - asset: assets/fonts/league/ostrich-sans-dashed.ttf
        - asset: assets/fonts/league/OstrichSansDashed-Medium.otf
    - family: GoudyStM
      fonts:
        - asset: assets/fonts/league/GoudyStM-webfont.ttf
        - asset: assets/fonts/league/GoudyStM-Italic-webfont.ttf
          style: italic
        - asset: assets/fonts/league/OFLGoudyStM.otf
        - asset: assets/fonts/league/OFLGoudyStM-Italic.otf
          style: italic
        - asset: assets/fonts/league/OFLGoudyStMTT.ttf
        - asset: assets/fonts/league/OFLGoudyStMTT-Italic.ttf
          style: italic
    - family: Kyiv Type Sans
      fonts:
        - asset: assets/fonts/fontesk/KyivType-VariableGX/KyivTypeSans-VarGX.ttf
    - family: Kyiv Type Serif
      fonts:
        - asset: assets/fonts/fontesk/KyivType-VariableGX/KyivTypeSerif-VarGX.ttf
    - family: Kyiv Type Titling
      fonts:
        - asset: assets/fonts/fontesk/KyivType-VariableGX/KyivTypeTitling-VarGX.ttf
    - family: Valiant
      fonts:
        - asset: assets/fonts/fontesk/VALIANT.otf
    - family: Starlance
      fonts:
        - asset: assets/fonts/fontesk/STARLANCE.ttf
    - family: Farabee Straight
      fonts:
        - asset: assets/fonts/fontesk/Farabee Straight Black.ttf
          weight: 900
        - asset: assets/fonts/fontesk/Farabee Straight Bold.ttf
          weight: 700
        - asset: assets/fonts/fontesk/Farabee Straight Semibold.ttf
          weight: 600
        - asset: assets/fonts/fontesk/Farabee Straight Medium.ttf
          weight: 500
        - asset: assets/fonts/fontesk/Farabee Straight Regular.ttf
          weight: 400
        - asset: assets/fonts/fontesk/Farabee Straight Light.ttf
          weight: 300
        - asset: assets/fonts/fontesk/Farabee Straight Thin.ttf
          weight: 100
    - family: Farabee
      fonts:
        - asset: assets/fonts/fontesk/Farabee Black.ttf
          weight: 900
        - asset: assets/fonts/fontesk/Farabee Bold.ttf
          weight: 700
        - asset: assets/fonts/fontesk/Farabee Semibold.ttf
          weight: 600
        - asset: assets/fonts/fontesk/Farabee Medium.ttf
          weight: 500
        - asset: assets/fonts/fontesk/Farabee Regular.ttf
          weight: 400
        - asset: assets/fonts/fontesk/Farabee Light.ttf
          weight: 300
        - asset: assets/fonts/fontesk/Farabee Thin.ttf
          weight: 100
    - family: Super Jellyfish
      fonts:
        - asset: assets/fonts/fontesk/Super Jellyfish.ttf
    - family: Vaganov SP Demo
      fonts:
        - asset: assets/fonts/fontesk/VaganovSPDemo-Bold.otf
          weight: 700
    - family: Ballast Stencil
      fonts:
        - asset: assets/fonts/fontesk/BallastStencil-Regular.otf
    - family: Parajanov
      fonts:
        - asset: assets/fonts/fontesk/Parajanov.ttf
    - family: Martius
      fonts:
        - asset: assets/fonts/fontesk/Martius.ttf
    - family: Super Brave
      fonts:
        - asset: assets/fonts/fontesk/Super Brave.ttf
    - family: Canalha
      fonts:
        - asset: assets/fonts/fontesk/Canalha-Bold.ttf
          weight: 700
        - asset: assets/fonts/fontesk/Canalha-Regular.ttf
          weight: 400
    - family: Beast
      fonts:
        - asset: assets/fonts/fontesk/Beast-Regular.otf
    - family: Lettertype
      fonts:
        - asset: assets/fonts/fontesk/Lettertype-Regular.otf
          weight: 400
        - asset: assets/fonts/fontesk/Lettertype-SemiBold.otf
          weight: 600
        - asset: assets/fonts/fontesk/Lettertype-Bold.otf
          weight: 700
        - asset: assets/fonts/fontesk/Lettertype-Italic.otf
          style: italic
        - asset: assets/fonts/fontesk/Lettertype-SemiBold-Italic.otf
          weight: 600
          style: italic
        - asset: assets/fonts/fontesk/Lettertype-Bold-Italic.otf
          weight: 700
          style: italic
    - family: FN Octahedron
      fonts:
        - asset: assets/fonts/fontesk/FN OCTAHEDRON v1.0.otf
    - family: DotMatrix Duo
      fonts:
        - asset: assets/fonts/fontesk/DotMatrixDuo-CondensedRegular.otf
    - family: Tintagel
      fonts:
        - asset: assets/fonts/fontesk/Tintagel.otf
    - family: Gotfridus
      fonts:
        - asset: assets/fonts/fontesk/Gotfridus.ttf
    - family: LT Basix
      fonts:
        - asset: assets/fonts/fontesk/LTBasix-Regular.ttf
    - family: Molten Display
      fonts:
        - asset: assets/fonts/fontesk/Molten Display.otf
    - family: Triform
      fonts:
        - asset: assets/fonts/fontesk/Triform.ttf
    - family: Groutpix Flow Serif
      fonts:
        - asset: assets/fonts/fontesk/GroutpixFlowSerif.ttf
    - family: Rhombic
      fonts:
        - asset: assets/fonts/fontesk/Rhombic.ttf
    - family: Nose Transport
      fonts:
        - asset: assets/fonts/fontesk/NoseTransport16-BoldDot.otf
          weight: 700
        - asset: assets/fonts/fontesk/NoseTransport16-RegularDot.otf
          weight: 400
        - asset: assets/fonts/fontesk/NoseTransport16-LightSquare.otf
          weight: 300
    - family: Outright
      fonts:
        - asset: assets/fonts/fontesk/Outright.otf
    - family: Moonet
      fonts:
        - asset: assets/fonts/fontesk/Moonet DEMO.otf
    - family: MYKA Tryba
      fonts:
        - asset: assets/fonts/fontesk/MYKA Tryba.ttf
    - family: Frontline
      fonts:
        - asset: assets/fonts/fontesk/Frontline-Regular.otf
          weight: 400
        - asset: assets/fonts/fontesk/Frontline-Italic.otf
          weight: 400
          style: italic
    - family: Jaro
      fonts:
        - asset: assets/fonts/fontesk/Jaro72pt-Regular.ttf
    - family: Tea Type
      fonts:
        - asset: assets/fonts/fontesk/Tea Type.otf
    - family: Moloko
      fonts:
        - asset: assets/fonts/fontesk/molokofont.otf
    - family: Tachyo
      fonts:
        - asset: assets/fonts/fontesk/Tachyo-1.0.0.otf
    - family: Scorn
      fonts:
        - asset: assets/fonts/fontesk/scorn.otf
    - family: Fasad
      fonts:
        - asset: assets/fonts/fontesk/Fasad-Regular.otf
    - family: Krease
      fonts:
        - asset: assets/fonts/fontesk/Krease-Display.otf
    - family: Beon
      fonts:
        - asset: assets/fonts/fontesk/Beon-Regular.otf
    - family: Gadems
      fonts:
        - asset: assets/fonts/fontesk/Gadems-PERSONALUSEONLY.otf
    - family: Grisha
      fonts:
        - asset: assets/fonts/fontesk/Grisha.ttf
    - family: Deserta
      fonts:
        - asset: assets/fonts/fontesk/Deserta.otf
    - family: Neon Sans
      fonts:
        - asset: assets/fonts/fontesk/NeonSans.otf
    - family: Rookworst
      fonts:
        - asset: assets/fonts/fontesk/Rookworst.ttf
    - family: Deadender
      fonts:
        - asset: assets/fonts/fontesk/DeadenderRegular.ttf
    - family: Klaxons
      fonts:
        - asset: assets/fonts/fontesk/Klaxons.otf
    - family: Starway
      fonts:
        - asset: assets/fonts/fontesk/Starway.otf
          weight: 400
        - asset: assets/fonts/fontesk/Starway-Light.otf
          weight: 300
        - asset: assets/fonts/fontesk/Starway-Bold.otf
          weight: 700
